
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: 🔔 checkout
      uses: actions/checkout@v4

    - name: 🔧 set up node
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: 📦 install dependencies
      run: npm ci

    - name: 🔨 build
      run: npm run build

    - name: 🧪 test
      run: npm test

