
name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'chase-moskal'
    steps:

    - name: 🔔 checkout
      uses: actions/checkout@v4

    - name: 🔧 set up node
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: 📦 install dependencies
      run: npm ci

    - name: 🔨 build
      run: npm run build

    - name: 🧪 test
      run: npm test

    - name: 🚀 npm publish
      uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.NPM_TOKEN }}

